namespace Obelisk.Agi
{
    /// <summary>
    /// Represents variables for AGI().
    /// </summary>
    public sealed class AgiVariableNames
    {
        /// <summary>
        /// The first argument that was passed to the AGI() or EAGI() application. For process-based AGI, this is the name of the AGI application that has been executed. For FastAGI, this would be the URL that was used to reach the FastAGI server.
        /// </summary>
        public const string REQUEST = "agi_request";

        /// <summary>
        /// The name of the channel that has executed the AGI() or EAGI() application.
        /// </summary>
        public const string CHANNEL = "agi_channel";

        /// <summary>
        /// The language set on agi_channel.
        /// </summary>
        public const string LANGUAGE = "agi_language";

        /// <summary>
        /// The channel type for agi_channel.
        /// </summary>
        public const string TYPE = "agi_type";

        /// <summary>
        /// The uniqueid of agi_channel.
        /// </summary>
        public const string UNIQUEID = "agi_uniqueid";

        /// <summary>
        /// The Asterisk version in use.
        /// </summary>
        public const string VERSION = "agi_version";

        /// <summary>
        /// The full caller ID string that is set on agi_channel.
        /// </summary>
        public const string CALLERID = "agi_callerid";

        /// <summary>
        /// The caller ID name that is set on agi_channel.
        /// </summary>
        public const string CALLERIDNAME = "agi_calleridname";

        /// <summary>
        /// The caller presentation associated with the caller ID set on agi_channel. For more information, see the output of core show function CALLERPRES at the Asterisk CLI.
        /// </summary>
        public const string CALLINGPRES = "agi_callingpres";

        /// <summary>
        /// The caller ANI2 associated with agi_channel.
        /// </summary>
        public const string CALLINGANI2 = "agi_callingani2";

        /// <summary>
        /// The caller ID TON (Type of Number) associated with agi_channel.
        /// </summary>
        public const string CALLINGTON = "agi_callington";

        /// <summary>
        /// The dialed number TNS (Transit Network Select) associated with agi_channel.
        /// </summary>
        public const string CALLINGTNS = "agi_callingtns";

        /// <summary>
        /// The dialed number associated with agi_channel.
        /// </summary>
        public const string DNID = "agi_dnid";

        /// <summary>
        /// The redirecting number associated with agi_channel.
        /// </summary>
        public const string RDNIS = "agi_rdnis";

        /// <summary>
        /// The context of the dialplan that agi_channel was in when it executed the AGI() or EAGI() application.
        /// </summary>
        public const string CONTEXT = "agi_context";

        /// <summary>
        /// The extension in the dialplan that agi_channel was executing when it ran the AGI() or EAGI() application.
        /// </summary>
        public const string EXTENSION = "agi_extension";

        /// <summary>
        /// The priority of agi_extension in agi_context that executed AGI() or EAGI().
        /// </summary>
        public const string PRIORITY = "agi_priority";

        /// <summary>
        /// An indication of whether AGI() or EAGI() was used from the dialplan. 0.0 indicates that AGI() was used. 1.0 indicates that EAGI() was used.
        /// </summary>
        public const string ENHANCED = "agi_enhanced";

        /// <summary>
        /// The accountcode associated with agi_channel.
        /// </summary>
        public const string ACCOUNTCODE = "agi_accountcode";

        /// <summary>
        /// The threadid of the thread in Asterisk that is running the AGI() or EAGI() application. This may be useful for associating logs generated by the AGI application with logs generated by Asterisk, since the Asterisk logs contain thread IDs.
        /// </summary>
        public const string THREADID = "agi_threadid";

        /// <summary>
        /// These variables provide the contents of the additional arguments provided to the AGI() or EAGI() application.
        /// </summary>
        public const string CUSTOM_ARG_PREFIX = "agi_arg_";
    }

    /// <summary>
    /// Represents variables for FastAGI().
    /// </summary>
    public sealed class FastAgiVariableNames
    {
        /// <summary>
        /// The script that is associated.
        /// </summary>
        public const string NETWORK_SCRIPT = "agi_network_script";
    }
}
